import { defineActionTypes } from '@capillarytech/vulcan-react-sdk/utils';

const scope = '/Components/pages/Products/';

export const actionTypes = defineActionTypes(
  {
    FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
    CREATE_PRODUCT_REQUEST: 'CREATE_PRODUCT_REQUEST',
    CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILURE: 'CREATE_PRODUCT_FAILURE',
    UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILURE: 'UPDATE_PRODUCT_FAILURE',
    DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',
    SET_SEARCH_FILTER: 'SET_SEARCH_FILTER',
    SET_BRAND_FILTER: 'SET_BRAND_FILTER',
    SET_CATEGORY_FILTER: 'SET_CATEGORY_FILTER',
    SET_STATUS_FILTER: 'SET_STATUS_FILTER',
    FETCH_BRANDS_FOR_FILTER_REQUEST: 'FETCH_BRANDS_FOR_FILTER_REQUEST',
    FETCH_BRANDS_FOR_FILTER_SUCCESS: 'FETCH_BRANDS_FOR_FILTER_SUCCESS',
    FETCH_CATEGORIES_FOR_FILTER_REQUEST: 'FETCH_CATEGORIES_FOR_FILTER_REQUEST',
    FETCH_CATEGORIES_FOR_FILTER_SUCCESS: 'FETCH_CATEGORIES_FOR_FILTER_SUCCESS',
    CLEAR_DATA: 'CLEAR_DATA',
  },
  { prefix: CURRENT_APP_NAME, scope: scope },
);
