import { defineActionTypes } from '@capillarytech/vulcan-react-sdk/utils';

const scope = '/Components/pages/Brands/';

export const actionTypes = defineActionTypes(
  {
    FETCH_BRANDS_REQUEST: 'FETCH_BRANDS_REQUEST',
    FETCH_BRANDS_SUCCESS: 'FETCH_BRANDS_SUCCESS',
    FETCH_BRANDS_FAILURE: 'FETCH_BRANDS_FAILURE',
    CREATE_BRAND_REQUEST: 'CREATE_BRAND_REQUEST',
    CREATE_BRAND_SUCCESS: 'CREATE_BRAND_SUCCESS',
    CREATE_BRAND_FAILURE: 'CREATE_BRAND_FAILURE',
    UPDATE_BRAND_REQUEST: 'UPDATE_BRAND_REQUEST',
    UPDATE_BRAND_SUCCESS: 'UPDATE_BRAND_SUCCESS',
    UPDATE_BRAND_FAILURE: 'UPDATE_BRAND_FAILURE',
    DELETE_BRAND_REQUEST: 'DELETE_BRAND_REQUEST',
    DELETE_BRAND_SUCCESS: 'DELETE_BRAND_SUCCESS',
    DELETE_BRAND_FAILURE: 'DELETE_BRAND_FAILURE',
    SET_SEARCH_FILTER: 'SET_SEARCH_FILTER',
    CLEAR_DATA: 'CLEAR_DATA',
  },
  { prefix: CURRENT_APP_NAME, scope: scope },
);
